# fly.toml app configuration file generated for annos on 2025-05-13T18:45:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'annos'
primary_region = 'sea'

[build]

# Define different process types
[processes]
  web = "npm start"
  feed-worker = "npm run worker:feeds"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']  # Only web processes handle HTTP traffic

# Default VM configuration for all processes
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Override VM settings for worker processes
[[vm]]
  processes = ['feed-worker']
  memory = '512mb'  # Workers typically need less memory
  cpu_kind = 'shared'
  cpus = 1

[env]
NODE_ENV="dev"
BASE_URL="https://api.dev.semble.so"
HOST="0.0.0.0"
APP_URL="https://dev.semble.so"
