name: Lint and Format Check

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install webapp dependencies
        run: cd src/webapp && npm ci
      
      - name: Check formatting (root)
        run: npm run format:check
      
      - name: Lint (root)
        run: npm run lint
      
      - name: Lint webapp
        run: cd src/webapp && npm run lint
