name: Lint and Format Check

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache node_modules (root)
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-root-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-root-

      - name: Cache node_modules (webapp)
        uses: actions/cache@v4
        with:
          path: src/webapp/node_modules
          key: ${{ runner.os }}-node-webapp-${{ hashFiles('src/webapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-webapp-

      - name: Install root dependencies
        run: npm ci

      - name: Install webapp dependencies
        run: cd src/webapp && npm ci

      - name: Check formatting (root)
        run: npm run format:check

      - name: Lint (root)
        run: npm run lint

      - name: Lint webapp
        run: cd src/webapp && npm run lint
